language: node_js
dist: trusty
sudo: required
node_js: stable
env:
  - PATH=$HOME/purescript:$PATH
install: |
  npm install -g pulp bower purescript
  bower install
script: |
  pulp test
  RESOLUTIONS=$(mktemp) &&
    bower list --json --offline > $RESOLUTIONS &&
    purs publish --dry-run --manifest bower.json --resolutions $RESOLUTIONS
